name: Build site and push to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configuring build Environment
      run: |
        sudo apt-get update

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Installing dependencies
      run: |
        gem install jekyll jekyll-remote-theme jekyll-sass-converter

    - name: Build site
      run: |
        cd site && jekyll b && cd ..

    - name: Push to gh-pages branch
      if: github.ref == 'refs/heads/main'
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.MLC_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git config --global user.email "mlc-gh-actions-bot@nomail"
        git config --global user.name "mlc-gh-actions-bot"

        ./scripts/gh_deploy_site.sh